### ISSUE TITLE
No such module 'Mockingbird'

### ISSUE THREAD

**Issue by nickcurran** [birdrides/mockingbird#6]
## Description

1. I installed to my Xcode 11 workspace for my iOS project with File -> Swift Packages -> Add Package Dependency...
2. Selected my Unit Test target along the way
3. Seemed to integrate fine
4. Installed generator from source and ran the Automated Integration steps, seems integrated and mocks are generated automatically
5. When I try to test, it errors on the first line `@testable import Mockingbird` in my AppMocks.generated.swift file.

## Environment

* Mockingbird CLI version 0.7.0
* Xcode 11.1 on macOS Catalina beta (19A582a)

**Comment by andrewchang-bird** [comment]
Thanks for the report, Nick! I’ve identified the issue and am working on a fix.

**Comment by andrewchang-bird** [comment]
Should be fixed in `0.7.2`

**Comment by sj1914** [comment]
Hi there i'm running on mockingjay 0.16 but am experiencing this same issue

**Comment by sj1914** [comment]
hi there! I've recently installed this version 0.16 into my repository using cocoapods, and am seeing the exact issue described above. Is there anything i could do to prevent this? I have uninstalled and reinstalled and am still facing the issue. Xcode version 12.3
